create table country(
                        id bigint generated by default as identity primary key,
                        name varchar(255),
                        continent varchar(255)
);

create table author(
                       id bigint generated by default as identity primary key,
                       name varchar(255),
                       surname varchar(255),
                       country_id bigint references country
);

create table book(
                     id bigint generated by default as identity primary key,
                     name varchar(255),
                     category varchar(255),
                     author_id bigint references author
);

create table wishlist(
                         id bigint generated by default as identity primary key
);

create table wishlist_book(
                              wishlist_id bigint references wishlist on delete cascade on update cascade,
                              book_id bigint references book on delete cascade on update cascade,
                              primary key (wishlist_id, book_id)
);

create table users(
                      id bigint generated by default as identity primary key,
                      username varchar(255),
                      password varchar(255),
                      name varchar(255),
                      surname varchar(255),
                      role varchar(255),
                      wishlist_id bigint references wishlist
);
